// DB KEYS & CONSTANTS
export const DB_KEYS = {
  BOOKS: 'lumina_books',
  USERS: 'lumina_users',
  LOANS: 'lumina_loans',
  PURCHASES: 'lumina_purchases',
  QUOTES: 'lumina_quotes',
  REVIEWS: 'lumina_reviews',
  FAVORITES: 'lumina_favorites',
  COUPONS: 'lumina_coupons',
  USER: 'lumina_current_user',
  PENDING_BORROWS: 'lumina_pending_borrows',
  PENDING_EXTENSIONS: 'lumina_pending_extensions'
};

export const translations = {
  tr: {
    navHome: 'Ana Sayfa',
    navCatalog: 'Katalog',
    navQuotes: 'Alıntı Defteri',
    navAbout: 'Hakkımızda',
    navFaq: 'S.S.S.',
    heroBadge: 'EDİTORYAL SEÇKİ · 2026 ARŞİVİ',
    heroTitle: 'Seçilmiş Eserler. Sessiz Bir Zihin.',
    heroSub: 'Fiziksel kütüphane disiplinini çağdaş dijital okuma kültürüyle buluşturan bağımsız bir edebiyat platformu.',
    heroBtn1: 'Koleksiyonu İncele →',
    heroBtn2: 'Okur Defterini Aç',
    moodTitle: 'Edebi Tercihe Göre Keşif.',
    moodSub: 'Hangi edebiyat disiplinine odaklanmak istersiniz?',
    featuredTitle: 'Haftanın Editoryal Seçkisi.',
    featuredSub: 'Küratörlerimiz ve okurlarımız tarafından öne çıkarılan eserler.',
    featuredAll: 'Tüm Koleksiyon →',
    catalogTitle: 'Kütüphane Kataloğu.',
    catalogSub: 'Tüm eserleri inceleyin, ödünç alın veya arşivinize dahil edin.',
    searchPlaceholder: 'Kitap adı, yazar veya ISBN ara...',
    allGenres: 'Tüm Türler',
    quotesEyebrow: 'LUMINA / OKUR ARŞİVİ',
    quotesTitle: 'Okur Defteri & Alıntılar.',
    quotesSub: 'Kütüphane koleksiyonundaki eserlerden altı çizilen, düşündüren edebi pasajlar.',
    quotesAddBtn: '+ Yeni Alıntı Kaydet',
    quoteSearchPlaceholder: 'Alıntı veya kitap ara...',
    quoteAllTags: 'Tüm Etiketler',
    aboutEyebrow: 'LUMINA / KURULUŞ & FELSEFE',
    aboutTitle: 'Kütüphane Hakkında.',
    aboutSub: 'Yazılı kültürün kalıcılığına ve bilinçli okuma eylemine adanmış bağımsız bir edebiyat ekosistemi.',
    aboutValuesTitle: 'Temel İlkelerimiz & Değerlerimiz',
    aboutValuesSub: 'Lumina kütüphane ekosistemini ayakta tutan sekiz ana sütun.',
    faqEyebrow: 'LUMINA / REHBER & BİLGİ',
    faqTitle: 'Sıkça Sorulan Sorular.',
    faqSub: 'Üyelik hakları, ödünç alma periyotları ve kütüphane işleyişine dair tüm detaylar.',
    favTitle: 'Kişisel Okuma Listeniz.',
    favSub: 'Daha sonra incelemek veya arşivinize katmak üzere kaydettiğiniz eserler.',
    cartTitle: 'Sipariş & Teslimat Özeti.',
    cartSub: 'Seçtiğiniz eserleri güvenle sipariş ederek kütüphanenize dahil edin.',
    btnDetail: 'Detayları İncele',
    btnBorrow: 'Ödünç Al',
    btnAddToCart: 'Sepete Ekle',
    btnBuy: 'Satın Al'
  },
  en: {
    navHome: 'Home',
    navCatalog: 'Catalog',
    navQuotes: 'Quotes Journal',
    navAbout: 'About Us',
    navFaq: 'FAQ',
    heroBadge: 'EDITORIAL SELECTION · 2026 ARCHIVE',
    heroTitle: 'Selected Literature. A Quiet Mind.',
    heroSub: 'An independent literary platform uniting physical library discipline with contemporary digital reading.',
    heroBtn1: 'Explore Collection →',
    heroBtn2: 'Open Reading Journal',
    moodTitle: 'Literary Direction.',
    moodSub: 'Select your preferred reading journey.',
    featuredTitle: 'Weekly Editorial Selection.',
    featuredSub: 'Works highlighted by our curators and readers.',
    featuredAll: 'Complete Archive →',
    catalogTitle: 'Library Catalog.',
    catalogSub: 'Explore, borrow, or acquire from the complete archive.',
    searchPlaceholder: 'Search book title, author, or ISBN...',
    allGenres: 'All Genres',
    quotesEyebrow: 'LUMINA / READER ARCHIVE',
    quotesTitle: 'Reading Journal & Passages.',
    quotesSub: 'Profound lines and highlighted thoughts from the collection.',
    quotesAddBtn: '+ Record New Quote',
    quoteSearchPlaceholder: 'Search quote or book...',
    quoteAllTags: 'All Tags',
    aboutEyebrow: 'LUMINA / HERITAGE & PHILOSOPHY',
    aboutTitle: 'About the Library.',
    aboutSub: 'An independent sanctuary devoted to the permanence of written culture and mindful reading.',
    aboutValuesTitle: 'Our Core Principles & Values',
    aboutValuesSub: 'Eight foundational pillars sustaining the Lumina ecosystem.',
    faqEyebrow: 'LUMINA / GUIDE & KNOWLEDGE',
    faqTitle: 'Frequently Asked Questions.',
    faqSub: 'Everything about borrowing periods, membership tiers, and library protocols.',
    favTitle: 'Your Reading List.',
    favSub: 'Curated works saved for future study and acquisition.',
    cartTitle: 'Order & Acquisition Summary.',
    cartSub: 'Acquire selected literature directly into your private archive.',
    btnDetail: 'View Details',
    btnBorrow: 'Borrow',
    btnAddToCart: 'Add to Cart',
    btnBuy: 'Purchase'
  }
};

export const summaries = {
  'Roman': 'Hayatın içinden karakterler, duygu yüklü duraklar ve akılda kalan bir insanlık yolculuğu anlatısı.',
  'Felsefe': 'Soru sormaya, varoluşu düşünmeye ve dünyaya yepyeni bir pencereden bakmaya davet eden derinlikli bir eser.',
  'Bilim Kurgu': 'Bilinen evrenin sınırlarını zorlayan, yapay zekâ, zaman ve hayal gücünün kesiştiği heyecan verici bir gelecek kurgusu.',
  'Klasik': 'Zamanın aşındıramadığı, her okumada yeni katmanlar ve anlamlar sunan dünya edebiyatının başyapıtlarından.',
  'Tarih': 'Geçmişin tozlu sayfalarını aydınlatarak bugünün dünyasını anlamamıza rehberlik eden kapsamlı bir araştırma.',
  'Psikoloji': 'İnsan zihninin derinliklerine, bilinçdışı motivasyonlara ve içsel dengeye ışık tutan zihin açıcı bir rehber.',
  'Şiir & Sanat': 'Kelimelerin ahenginde kaybolacağınız, estetik duyarlılığı ve ruhsal inceliği yücelten dizeler.',
  'Gizem & Polisiye': 'Her sayfasında merak dozunu artıran, zekice kurgulanmış ipuçları ve beklenmedik ters köşeler.',
  'Biyografi': 'Tarihe ve edebiyata yön vermiş ilham veren karakterlerin bilinmeyen yönlerini aktaran hayat anlatısı.',
  'Mitoloji': 'Antik tanrıların, efsanevi kahramanların ve insanlığın varoluş serüveninin anlatıldığı kadim efsaneler.'
};
